django_movie/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movies.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
]

movies/models.py
from django.db import models
from datetime import date

from django.urls import reverse


class Category(models.Model):
    # Категорії
    name = models.CharField("Категорія", max_length=150)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорії"
        verbose_name_plural = "Категорії"


class Actor(models.Model):
    # Актори та режисери
    name = models.CharField("Ім'я", max_length=100)
    age = models.PositiveSmallIntegerField("Вік", default=0)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актори та режисери"
        verbose_name_plural = "Актори та режисери"


class Genre(models.Model):
    # Жанри
    name = models.CharField("Ім'я", max_length=100)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанри"


class Movie(models.Model):
    # Фільм
    title = models.CharField("Назва", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Опис")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата виходу", default=2019)
    country = models.CharField("Країна", max_length=30)
    directors = models.ManyToManyField(
        Actor, verbose_name="режисер", related_name="film_director")
    actors = models.ManyToManyField(
        Actor, verbose_name="актори", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанри")
    world_premiere = models.DateField("Прем'єра в світі", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0,
                                         help_text="Вказувати суму в доларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сбори в США", default=0, help_text="Вказувати суму в доларах"
    )
    fess_in_world = models.PositiveIntegerField(
        "Сбори в світі", default=0, help_text="Вказувати суму в доларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категорії", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Чернетка", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фільм"
        verbose_name_plural = "Фільми"


class MovieShots(models.Model):
    # Кадри з Фільму
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to="movie_shots/")
    movie = models.ForeignKey(
        Movie, verbose_name="Фільм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фільму"
        verbose_name_plural = "Кадри из фільму"


class RatingStar(models.Model):
    # Зірка рейтингу
    value = models.SmallIntegerField("Значення", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Зірка рейтингу"
        verbose_name_plural = "Зірка рейтингу"
        ordering = ["-value"]


class Rating(models.Model):
    # Рейтинг
    ip = models.CharField("IP адреса", max_length=15)
    star = models.ForeignKey(
        RatingStar, on_delete=models.CASCADE, verbose_name="зірка")
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, verbose_name="фільм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    # Відгуки
    email = models.EmailField()
    name = models.CharField("Ім'я", max_length=100)
    text = models.TextField("Повідомлення", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родич", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(
        Movie, verbose_name="Фільм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"

movies/forms.py
from django import forms

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    # Форма для відгуків

    class Meta:
        model = Reviews
        fields = ("name", "email", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }


class RatingForm(forms.ModelForm):
    # Додавання рейтингу
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.conf import settings
from django.db import models
from django.db.models import Q, OuterRef, Subquery, Case, When
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Movie, Category, Actor, Genre, Rating, Reviews
from .forms import ReviewForm


class MoviesView(ListView):
    # Список фільмів
    model = Movie
    queryset = Movie.objects.filter(draft=False)


class MovieDetailView(DetailView):
    # Повний опис
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    slug_field = "url"


class AddReview(View):
    # Відгуки
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())

templates/base.html
<!DOCTYPE html>
{% load static recaptcha3 %}
<html lang="">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->

      {% recaptcha_init %}
      {% recaptcha_ready action_name='homepage' %}
</head>
<body>
<div id="page" class="page">
    <div class="main-banner bg {% block header %}  {% endblock header %}" id="home">
        {% include 'include/header.html' %}
    </div>
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="index.html" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
    </ol>
    {% block content %}

    {% endblock content %}
    {% include 'include/footer.html' %}
</div>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/include/footer.html
{% load contact_tags %}
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true">
                                    Сайт про кіно
                                </span>
                    </a>
                </h2>
                <p class="editContent">
                    Сайт для створення кіношного контенту
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent">
                            <span class="fa fa-facebook-f"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent">
                            <span class="fa fa-twitter"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent">
                            <span class="fa fa-dribbble"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent">
                            <span class="fa fa-google-plus"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    {% contact_form %}
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                            Розділи</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="index.html" class="editContent">Головна</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent">Категорії</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent">Контакти</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                                Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">
                            Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent">Email </h4>
                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a>
                                </p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent">Location</h4>
                                <p class="editContent">New York City</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- //footer -->

templates/include/header.html
{% load i18n movie_tag %}
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1><a href="index.html" class="editContent"
                       style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: Source Sans Pro;, sans-serif;">DjangoMovie</a>
                </h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="index.html">Головна</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Категорії <span
                            class="fa fa-angle-down" aria-hidden="true"></span> </label>
                    <a href="#">Категорії <span class="fa fa-angle-down"
                                                aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        {% get_categories as categories %}
                        {% for category in categories %}
                            <li><a href="/">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    {% if user.is_authenticated %}
                        <span>{{ user.username }}</span>
                        <a href="{% url 'account_logout' %}"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                            Вихід
                        </a>
                    {% else %}
                        <a href="{% url 'account_login' %}"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                            Вхід
                        </a>
                         <a href="{% url 'account_signup' %}"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                            Реєстрація
                        </a>
                    {% endif %}
                </li>

                <li>
                    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <select name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                        selected{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="Go">
                    </form>
                </li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
<!-- //header -->
<!--/banner-->
<div class="banner-info">
    <p class="editContent">Сайт на Django</p>
    <h3 class="mb-4 editContent">Все про кіно</h3>
    <div class="ban-buttons">


    </div>
</div>
<!--// banner-inner -->

templates/include/sidebar.html
{% load movie_tag %}
<div class="search-bar w3layouts-newsletter">
    <h3 class="sear-head editContent">Пошук фільму</h3>
    <form action="{% url 'search' %}" method="get" class="d-flex editContent">
        <input type="search" placeholder="Введіть назву..." name="q" class="form-control" required="">
        <button type="submit" class="btn1 btn">
            <span class="fa fa-search" aria-hidden="true"></span>
        </button>
    </form>
</div>
<!--preference -->
<form action="{% url 'filter' %}" method="get" name="filter">
    <div class="left-side my-4">
        <h3 class="sear-head editContent">Жанры</h3>
        <ul class="w3layouts-box-list">
            {% for genre in view.get_genres %}
                <li class="editContent">
                    <input type="checkbox" class="checked" name="genre" value="{{ genre.id }}">
                    <span class="span editContent">{{ genre.name }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- // preference -->
    <!-- discounts -->

    <div class="left-side">
        <h3 class="sear-head editContent">Год</h3>
        <ul class="w3layouts-box-list">
            {% for movie in view.get_years %}
                <li class="editContent">
                    <input type="checkbox" class="checked" name="year" value="{{ movie.year }}">
                    <span class="span editContent">{{ movie.year }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <button type="submit">Знайти</button>
</form>
<!-- //discounts -->
<!-- reviews -->
<div class="customer-rev left-side my-4">
    <h3 class="sear-head editContent">Рейтинг</h3>
    <ul class="w3layouts-box-list">
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="editContent">5.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">4.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.5</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">2.5</span>
            </a>
        </li>
    </ul>
</div>
{% get_last_movies count=3 %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static i18n %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>{% trans 'Рік' %}:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Країна' %}:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Слоган' %}:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Режисер' %}:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{ director.get_absolute_url }}">
                                    {{ director.name }}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>{% trans 'Актори' %}:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">
                                    {{ actor.name }}
                            </a>
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>{% trans 'Жанр' %}:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>{% trans "Прем'єра у світі" %}:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li>
                        <span><b>{% trans 'Бюджет' %}:</b> ${{ movie.budget }}</span></li>
                    <li>
                        <span><b>{% trans 'Сбори у США' %}:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li>
                        <span><b>{% trans 'Сбори у світі' %}:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>{% trans 'Рейтинг' %}:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
                        </form>
                    </li>
                </ul>

                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                   <!--
                                    <span class="fa fa-vk"></span>
                                    -->
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                {% trans 'Про фільм'  %} {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>
                        {% trans 'Лишити відгук ' %}
                    </h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш коментар *
                            </label>
                            {{ form.text }}
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    І'мя *
                                </label>
                                {{ form.name }}
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                {{ form.email }}
                            </div>
                            {{ form.captcha }}
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Відправити
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid "
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }

    </script>
{% endblock movie %}